layout_spectrum: 0.6948121
typography_spectrum: 0.9085586
color:
  saturation: 0.5857259
  lightness: 0.224043
  brandStrength: 0.3564737
  rhythmicContrast: 0.6738871
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Ooosh
